version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    container_name: event-app-frontend
    ports:
      - "3000:3000"
    networks:
      - common-network
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    container_name: event-app-backend
    ports:
      - "5001:5000"
    networks:
      - common-network
    env_file:
      - .env
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eventsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./event-app/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - common-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8083:80"
    depends_on:
      - postgres-db
    networks:
      - common-network

networks:
  common-network:
    external: true

volumes:
  postgres-data:
