version: '3.9'

services:
  solace:
    container_name: solace
    image: solace/solace-pubsub-standard:latest
    volumes:
      - "solace:/var/lib/solace"
    shm_size: 1g
    ulimits:
      core: -1
      nofile:
        soft: 2448
        hard: 6592
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
    ports:
      - 8008:8008
      - 1443:1443
      - 1943:1943
      - 1883:1883
      - 5671:5671
      - 5672:5672
      - 8005:8000
      - 8442:8443
      - 8883:8883
      - 8081:8080
      - 9000:9000
      - 9443:9443
      - 55554:55555
      - 55050:55003
      - 55443:55443
      - 2222:2222
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
      start_interval: 5s
    networks:
      - common-network

  solace-init:
    build:
      context: ./solace/
      dockerfile: Dockerfile
    container_name: solace-init
    restart: "no"
    depends_on:
      solace:
        condition: service_healthy
    networks:
      - common-network

networks:
  common-network:
    external: true

volumes:
  solace:
