version: '3.9'

services:
  subscriber0:
    container_name: test-sub-birth-queue
    build:
      context: ./NEMS_Test_Subscriber/
      dockerfile: Dockerfile
    environment:
      - nems.broker.queue=Birth
    networks:
      - common-network

  subscriber1:
    container_name: test-sub-death-queue
    build:
      context: ./NEMS_Test_Subscriber/
      dockerfile: Dockerfile
    environment:
      - nems.broker.queue=Death
    networks:
      - common-network

  subscriber2:
    container_name: test-sub-enrollment-queue
    build:
      context: ./NEMS_Test_Subscriber/
      dockerfile: Dockerfile
    environment:
      - nems.broker.queue=Enrollment
    networks:
      - common-network

networks:
  common-network:
    external: true
